baseURL = 'https://tean-lai.github.io/'  # 'http://localhost:1313/'
languageCode = 'en-us'
title = "Tean's Website"
theme = "hugo-theme-terminal"
pagination.pagerSize = 5  # not sure what this does
[params]
  brand = "Tean Lai"
  description = "a website"
  centerTheme = true
  showLastUpdated = true
  updatedDatePrefix = "Updated"
  Toc = false
[markup.highlight]
  noClasses = false  # Required for Chroma and custom syntax highlighting
[languages]
  [languages.en.params.logo]
    logoText = "Tean"
    logoHomeLink = "/"
  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "thoughts"
      name = "Thoughts"
      url = "/thoughts"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "wiki"
      name = "Wiki"
      url = "/wiki"
      weight = 3
    [[languages.en.menu.main]]
      identifier = "professional"
      name = "Professional"
      url = "/pro-tean"
      weight = 4
[markup.goldmark.renderer]
  unsafe = true