baseURL = 'https://tean-lai.github.io/'
# baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = "Tean's Website"
theme = "poison"

[params]
#   hideToc = true
  brand = "Tean Lai"
  description = "a website"
  dark_mode = true
  menu = [
    { Name = "About", URL = "/", HasChildren = false },
    { Name = "Thoughts", URL = "/thoughts/", HasChildren = false, Limit = 5},
  ]

# [menu]
#   [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1
# 
#   [[menu.main]]
#     name = "About Me"
#     url = "/about/"
#     weight = 2
# 
#   [[menu.main]]
#     name = "Thoughts"
#     url = "/thoughts/"
#     weight = 3